# Generated by Django 3.1 on 2020-08-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='imagen',
            field=models.ImageField(upload_to='adopcion'),
        ),
    ]
